data = struct;
data.Argentina = csv2struct('Argentina.csv');data.Belize = csv2struct('Belize.csv');
data.Bulgaria = csv2struct('Bulgaria.csv');data.Canada = csv2struct('Canada.csv');
data.Colombia = csv2struct('Colombia.csv');data.Cyprus = csv2struct('Cyprus.csv');
data.CzechRep = csv2struct('CzechRep.csv');data.England = csv2struct('England.csv');
data.France = csv2struct('France.csv');data.Germany= csv2struct('Germany.csv');
data.Greece = csv2struct('Greece.csv');data.HongKong= csv2struct('HongKong.csv');
data.Hungary = csv2struct('Hungary.csv');data.Iran= csv2struct('Iran.csv');
data.Italy = csv2struct('Italy.csv');data.Kuwait= csv2struct('Kuwait.csv');
data.Latvia= csv2struct('Latvia.csv');data.Lithuania = csv2struct('Lithuania.csv');
data.Macedonia = csv2struct('Macedonia.csv');data.Moldova= csv2struct('Morocco.csv');
data.Netherlands = csv2struct('Netherlands.csv');data.NewZealand= csv2struct('NewZealand.csv');
data.Romania = csv2struct('Romania.csv');data.Russia= csv2struct('Russia.csv');
data.Scotland = csv2struct('Scotland.csv');data.Singapore= csv2struct('Singapore.csv');
data.Slovakia = csv2struct('Slovakia.csv');data.Slovenia = csv2struct('Slovenia.csv');
data.Sweden = csv2struct('Sweden.csv');data.Turkey= csv2struct('Turkey.csv');
data.USA = csv2struct('USA.csv');data.Morocco = csv2struct('Morocco.csv');
data.Norway= csv2struct('Norway.csv');

[data.Argentina.number, ~] = size(data.Argentina.idcntry);[data.Belize.number, ~] = size(data.Belize.idcntry);
[data.Bulgaria.number, ~] = size(data.Bulgaria.idcntry);[data.Canada.number, ~] = size(data.Canada.idcntry);
[data.Colombia.number, ~] = size(data.Colombia.idcntry);[data.Cyprus.number, ~] = size(data.Cyprus.idcntry);
[data.CzechRep.number, ~] = size(data.CzechRep.idcntry);[data.England.number, ~] = size(data.England.idcntry);
[data.France.number, ~] = size(data.France.idcntry);[data.Germany.number, ~] = size(data.Germany.idcntry);
[data.Greece.number, ~] = size(data.Greece.idcntry);[data.HongKong.number, ~] = size(data.HongKong.idcntry);
[data.Hungary.number, ~] = size(data.Hungary.idcntry);[data.Iran.number, ~] = size(data.Iran.idcntry);
[data.Italy.number, ~] = size(data.Italy.idcntry);[data.Kuwait.number, ~] = size(data.Kuwait.idcntry);
[data.Latvia.number, ~] = size(data.Latvia.idcntry);[data.Lithuania.number, ~] = size(data.Lithuania.idcntry);
[data.Macedonia.number, ~] = size(data.Macedonia.idcntry);[data.Moldova.number, ~] = size(data.Moldova.idcntry);
[data.Morocco.number, ~] = size(data.Morocco.idcntry);[data.Netherlands.number, ~] = size(data.Netherlands.idcntry);
[data.NewZealand.number, ~] = size(data.NewZealand.idcntry);[data.Romania.number, ~] = size(data.Romania.idcntry);
[data.Russia.number, ~] = size(data.Russia.idcntry);[data.Scotland.number, ~] = size(data.Scotland.idcntry);
[data.Sweden.number, ~] = size(data.Sweden.idcntry);[data.Turkey.number, ~] = size(data.Turkey.idcntry);
[data.USA.number, ~] = size(data.USA.idcntry);[data.Norway.number, ~] = size(data.Norway.idcntry);
[data.Morocco.number, ~] = size(data.Morocco.idcntry);[data.Singapore.number, ~] = size(data.Singapore.idcntry);
[data.Slovakia.number, ~] = size(data.Slovakia.idcntry);[data.Slovenia.number, ~] = size(data.Slovenia.idcntry);


data.Argentina.title = 'ARG';data.Belize.title = 'BLZ';data.Bulgaria.title = 'BGR';
data.Canada.title = 'CAN';data.Colombia.title = 'COL';data.Cyprus.title = 'CYP';
data.CzechRep.title = 'CZE';data.England.title = 'ENG';data.France.title = 'FRA';
data.Germany.title = 'GER';data.Greece.title = 'GRC';data.HongKong.title = 'HKG';
data.Hungary.title = 'HUN';data.Iran.title = 'IRN';data.Italy.title = 'ITA';
data.Kuwait.title = 'KWT';data.Latvia.title = 'LVA';data.Lithuania.title = 'LTU';
data.Macedonia.title = 'MKD';data.Moldova.title = 'MDA';data.Morocco.title = 'MAR';
data.Netherlands.title = 'NLD';data.NewZealand.title = 'NZL';data.Romania.title = 'ROU';
data.Russia.title = 'RUS';data.Scotland.title = 'SCO';data.Sweden.title = 'SWE';
data.Turkey.title = 'TUR';data.USA.title = 'USA';data.Norway.title = 'NOR';
data.Morocco.title= 'MAR';data.Singapore.title = 'SGP';data.Slovakia.title = 'SVK';
data.Slovenia.title = 'SVN';
